### ISSUE TITLE
Feature request: convert SVG yaml block for other formats

### ISSUE THREAD

**Issue by m-guggenmos** [fradav/quarto-revealjs-animate#2]
For output formats other than revealjs, the yaml code block used to generate animated SVGs is displayed verbatim. It would be a nice addition if a code block of the form 

~~~
```yaml { .animate src="image.svg"}
setup:
  - element: "#xyz"
 ...
```
~~~

could be transformed to

~~~
![](image.svg)
~~~

Or ideally even transforming something like

~~~
```yaml { .animate .my-custom-class src="image.svg" caption="My custom caption"}
setup:
  - element: "#xyz"
 ...
```
~~~

to 

~~~
![My custom caption](image.svg){.my-custom-class}
~~~
